name: rx_lab
description: "The Reactive Programming Lab"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  web:
    generate: true
